# Pano.dev Netlify config

[build]
  publish = "build-output/"
  command = "gatsby build"
  functions = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # Multi-value headers are expressed with multi-line strings.
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

    # Basic-Auth allows you to password protect your whole site.
    # This feature may not be available on all plans.
    Basic-Auth = "pano:panoramic"
